name: laravel-deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      run: zip -r deploy.zip ./
      
    - name: Deploy to EBS
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: dlshop
        environment_name: Dlshop-env-1
        existing_bucket_name: elasticbeanstalk-ap-southeast-1-762161261983
        version_label: ${{ github.sha }}
        region: ap-southeast-2
        deployment_package: deploy.zip

